name: Periodic Check

on:
  push:
    branches:
      - master

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check periodic health url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-sirbh.fly.dev/periodic_health
          max-attempts: 2
          retry-delay: 10s